CREATE SEQUENCE OM_INCREMENT_SEQ_GENERATOR;

CREATE TABLE OM_TASK
(
    PRIORITY INTEGER NOT NULL,
    NAME     VARCHAR NOT NULL,
    UUID     VARCHAR NOT NULL,
    DATE     DATETIME,
    CONSTRAINT UNIQUE_NAME
        UNIQUE (NAME),
    PRIMARY KEY (UUID)
);
