CREATE TABLE TASK
(
    ID       BIGINT  NOT NULL,
    PRIORITY INTEGER NOT NULL,
    NAME     VARCHAR NOT NULL,
    UUID     VARCHAR NOT NULL,
    DATE     DATETIME,
    CONSTRAINT UNIQUE_NAME
        UNIQUE (NAME),
    CONSTRAINT PK_ID
        PRIMARY KEY (ID)
);
