CREATE TABLE TASK
(
    ID       BIGINT AUTO_INCREMENT NOT NULL,
    PRIORITY INTEGER NOT NULL,
    NAME     VARCHAR(255) NOT NULL,
    UUID     VARCHAR(255) NOT NULL,
    DATE     DATETIME,
    CONSTRAINT UNIQUE_NAME
        UNIQUE (NAME),
    CONSTRAINT PK_ID
        PRIMARY KEY (ID)
);
