CREATE TABLE USER_TASKS
(
    USER_ID BIGINT NOT NULL,
    TASK_ID BIGINT NOT NULL,

    CONSTRAINT PK_USER_TASKS_ID
        PRIMARY KEY (USER_ID, TASK_ID),
    CONSTRAINT FK_USER_ID
        FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    CONSTRAINT FK_TASK_ID
        FOREIGN KEY (TASK_ID) REFERENCES TASK (ID)
);
