CREATE TABLE USER
(
    ID         BIGINT       NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL,
    USER_UUID  VARCHAR(255) NOT NULL,

    CONSTRAINT PK_USER_ID
        PRIMARY KEY (ID)
);
